# Generated by Django 3.0.8 on 2020-07-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='media_id',
            field=models.CharField(default='hl2G467o', max_length=100),
            preserve_default=False,
        ),
    ]
