# Generated by Django 3.0.8 on 2020-07-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_clip_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='composer',
            field=models.CharField(default='Bach, Jean-Sébastien', max_length=100),
            preserve_default=False,
        ),
    ]
