# Generated by Django 3.0.8 on 2020-07-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_clip_composer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='jwplayer_url',
        ),
        migrations.AddField(
            model_name='clip',
            name='period',
            field=models.CharField(choices=[('BA', 'Baroque'), ('CL', 'Classique'), ('CO', 'Contemporain'), ('RO', 'Romantique')], default='Baroque', max_length=2),
            preserve_default=False,
        ),
    ]
