# Generated by Django 3.0.8 on 2020-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200714_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='period',
            field=models.CharField(choices=[('BA', 'Baroque'), ('CL', 'Classique'), ('CO', 'Contemporain'), ('RO', 'Romantique'), ('MO', 'Moderne')], max_length=2),
        ),
    ]
